account:
  initial-balance: 1000000000

account-api:
  base-url: ${ACCOUNT_API_URL}

debug: false

frontend:
  url: ${FE_URL}

jwt:
  secret-key: ${SECRET_KEY}

logging:
  level:
    arile.toy.stocksystem: debug
    org.springframework.web.service: debug

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

  streams:
    user:
      key: user-events

    order:
      prefix: order-events

    cancel:
      prefix: cancel-events

    auto-order:
      prefix: auto-order-events

    auto-cancel:
      prefix: auto-cancel-events

    trailing-stop:
      prefix: trailing-stop-events

    trailing-stop-cancel:
      prefix: trailing-stop-cancel-events

    otoco:
      prefix: otoco-events

    otoco-cancel:
      prefix: otoco-cancel-events

stock-groups:
  groups:
    A:
      - "005930"
      - "000660"
      - "005935"
    B:
      - "005380"
      - "373220"
      - "000250"
      - "196170"
      - "086520"
      - "247540"
      - "277810"
    CLOSE:
      - "125020"

spring:
  application.name: bff-server
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always
  task:
    scheduling:
      pool:
        size: 6

---

account:
  initial-balance: 1000000000

account-api:
  base-url: http://localhost:8082

jwt:
  secret-key: eDlsi387fhsEucu7xhsEehd8fys7ejcSdFeDF92w738lfskc8FejfDB38f==

frontend:
  url: test-fe-url

naver:
  client-id: test-client-id
  client-secret: test-client-secret

stock-groups:
  groups:
    A:
      - "005930"

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username:
    password:

redis:
  host: localhost
  port: 6379