api:
  approval-key-url: ${APPROVAL_KEY_URL}
  app-key: ${APP_KEY}
  app-secret: ${APP_SECRET}
  ws-url: ${WS_URL}

debug: false

logging:
  level:
    arile.toy.stocksystem: debug
    org.springframework.web.service: debug

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

  streams:
    user:
      key: user-events
      consumer-group: stock-group

    order:
      prefix: order-events
      consumer-group: stock-group

    cancel:
      prefix: cancel-events
      consumer-group: stock-group

    auto-order:
      prefix: auto-order-events
      consumer-group: stock-group

    auto-cancel:
      prefix: auto-cancel-events
      consumer-group: stock-group

server:
  port: 8081
  group: B

stock-groups:
  groups:
    A:
      - "005930"
      - "000660"
      - "005935"
    B:
      - "005380"
      - "373220"
      - "000250"
      - "196170"
      - "086520"
      - "247540"
      - "277810"
    CLOSE:
      - "125020"

spring:
  application.name: stock-server
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql.init.mode: always

---

api:
  approval-key-url: test-approval-key-url
  app-key: test-app-key
  app-secret: test-app-secret
  ws-url: test-ws-url

server:
  group: A

stock-groups:
  groups:
    A:
      - "005930"

    CLOSE: []

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username:
    password:

redis:
  host: localhost
  port: 6379