name: Terraform CD

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

jobs:
  terraform-cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/environments/dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init (real backend)
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="db_name=${{ secrets.DB_NAME }}" \
            -var="fe_url=${{ secrets.FE_URL }}" \
            -var="cloudfront_acm_arn=${{ secrets.CLOUDFRONT_ACM_ARN }}" \
            -var="alb_acm_arn=${{ secrets.ALB_ACM_ARN }}" \
            -var="app_key=${{ secrets.APP_KEY }}" \
            -var="app_secret=${{ secrets.APP_SECRET }}" \
            -var="approval_key_url=${{ secrets.APPROVAL_KEY_URL }}" \
            -var="secret_key=${{ secrets.SECRET_KEY }}" \
            -var="ws_url=${{ secrets.WS_URL }}"